@startuml

(Sacar dinero) as "Sacar dinero
--
+ solicitud hecha"
(Retener tarjeta)

note "Descripcion\n \n condicion:\n{historia sospechosa}\npunto de extension:\nsolicitud hecha" as N1

(Retener tarjeta)..N1
N1 ..>(Sacar dinero):<<Extend>>


@enduml