@startuml

:new Actor: as act
act -- (Identificarse)
act -- (Pagar)
act -- (Eligir mensajero)
act -- (Confirmar)

(Identificarse)<..(Registrarse):<<extend>>

(Pagar)<|--(Pagar con tarjeta)
(Pagar) <|-- (Pagar con transferencia)
@enduml